// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBapo1tPN7Eb4gK7krTsZ_QN2CnES4kdok',
    appId: '1:186567997698:android:51153309ab4c2d7eaa2a1b',
    messagingSenderId: '186567997698',
    projectId: 'fir-course-56630',
    storageBucket: 'fir-course-56630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0HU3Um1ZjFF3BOPCsdio224O56c6GBg',
    appId: '1:186567997698:ios:eb4610f812bdc175aa2a1b',
    messagingSenderId: '186567997698',
    projectId: 'fir-course-56630',
    storageBucket: 'fir-course-56630.appspot.com',
    iosBundleId: 'com.example.firebaseCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDysJnwoYi84o_vkjUJ1IKoXHS8sCHuzww',
    appId: '1:186567997698:web:9771337ea013e6eaaa2a1b',
    messagingSenderId: '186567997698',
    projectId: 'fir-course-56630',
    authDomain: 'fir-course-56630.firebaseapp.com',
    storageBucket: 'fir-course-56630.appspot.com',
    measurementId: 'G-56J9LVKLW8',
  );
}
